version: '3.1'

services:
  client-service:
    image: ion21/client-service:v2
    networks:
      - mynet
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: "http://localhost:5000"

networks:
  mynet:
    driver: bridge