#version: '3.1'
#
#services:
#  client-service:
#    image: ion21/client-service:v3
#    networks:
#      - mynet
#    ports:
#      - "3000:80"
#    environment:
#      NODE_ENV: development
#
#networks:
#  mynet:
#    driver: bridge

version: '3'
services:
  my-react-app:
    container_name: client-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - REACT_APP_PATH_TO=production

    ports:
      - "3000:3000"